language: node_js
node_js:
- 10
cache:
  npm: true
  directories:
  - ~/.cache
install:
- npm ci
script:
- npm run build
- npm run start &
- npm run test:e2e --headless --url=localhost:3000
- kill $(jobs -p) || true